title: 简单的快乐
description: An individual blog to share life experience
permalink: '/blog/:year/:month/:day/:title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rabbitxyt.github.io/" 

# Author Settings
author: Yiting Xiao # add your name
author-img: photo.jpg # add your photo
about-author: 我叫肖怡婷，90后，白羊座，来自上海。本科毕业后来到美国读研，也在这里遇见了自己的另一半。希望用这个小小的博客分享自己的学习和生活。 # add description
twitter: yiting_xiao # add your Twitter handle
facebook: yxiao82 # add your Facebook handle
github: rabbitxyt # add your Github handle
linkedin: yitingxiao # add your Linkedin handle
email: rabbitxyt@gmail.com # add your Email address
weibo: rabbitxyt

# Disqus
discus-identifier: #rabbitxyt # add your discus identifier

# Tracker
analytics: UA-107690772-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-feed 


paginate: 8
paginate_path: "/page/:num"

defaults:
  -
    scope:
      path: "photography"
    values:
      permalink: /:path/:basename:output_ext


exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
