title: 简单的快乐
description: An individual blog to share life experience
permalink: '/blog/:year/:month/:day/:title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" 

# Author Settings
author: Yiting Xiao # add your name
author-img: photo.jpg # add your photo
about-author: 92年生，来自上海，现居美国。有一个很厉害的正在读博的老公，一只无法无天的猫。想要努力成长，不管是学业上还是性格上，成为更好的自己。未来，用自己的经验教训好好教育下一代。感谢所有爱我的你们，给我源源不断的正能量。那么，希望我的博客能同样给你一点正能量。


# add description
twitter: yiting_xiao # add your Twitter handle
facebook: yxiao82 # add your Facebook handle
github: rabbitxyt # add your Github handle
linkedin: yitingxiao # add your Linkedin handle
email: rabbitxyt@gmail.com # add your Email address
weibo: rabbitxyt

# Disqus
discus-identifier: rabbitxyt # add your discus identifier

# Tracker
analytics: UA-107690772-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-feed 


paginate: 8
paginate_path: "/page/:num"

defaults:
  -
    scope:
      path: "photography"
    values:
      permalink: /:path/:basename:output_ext


exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
