title: 简单的快乐
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: '/blog/:year/:month/:day/:title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Yiting Xiao # add your name
author-img: photo.jpg # add your photo
about-author: 我叫肖怡婷，90后，白羊座，来自上海。本科毕业后来到美国读研，也在这里遇见了自己的另一半。希望用这个小小的博客分享自己的学习和生活。 # add description
twitter: yiting_xiao # add your Twitter handle
facebook: yxiao82 # add your Facebook handle
github: rabbitxyt # add your Github handle
linkedin: yitingxiao # add your Linkedin handle
email: rabbitxyt@gmail.com # add your Email address
weibo: rabbitxyt

# Disqus
discus-identifier: rabbitxyt # add your discus identifier

# Tracker
analytics: UA-107690772-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

defaults:
  -
    scope:
      path: "photography"
    values:
      permalink: /:path/:basename:output_ext


exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
